### ISSUE TITLE
Unable to extract JS player URL

### ISSUE THREAD

**Issue by Ramiferous** [deepjyoti30/ytmdl#127]
# Bug report
## Version Info

- Ytmdl version: 2020.11.20-1
- Youtube-dl version: 2020.11.21.1

## How Ytmdl was installed?
pip install ytmdl

## Console Log

```console
[ytmdl]:[22/11/2020 20:12:14]:  Logger running in DEBUG mode 
[ytmdl]:[22/11/2020 20:12:14]:  Passed args: Namespace(SONG_NAME=['in', 'a', 'gun', 'barrel'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song='fish', trim=False, url=None) 
[ytmdl]:[22/11/2020 20:12:14]:  ['in', 'a', 'gun', 'barrel'] 
[ytmdl]:[22/11/2020 20:12:14]:  in a gun barrel 
[cache]:[22/11/2020 20:12:14]:  Searching to see if already present in /home/david/Music 
[ytmdl]:[22/11/2020 20:12:14]:  proxy passed: None 
[ytmdl]:[22/11/2020 20:12:14]:  Passed format: mp3 
[ytmdl]:[22/11/2020 20:12:14]:  Searching Youtube for in a gun barrel 
[ytmdl]:[22/11/2020 20:12:16]:  {'title': 'NOFX - Fish in a Gun Barrel w/ Fat Mike introduction', 'href': '/watch?v=KY0MyjtV8mM', 'author_name': 'Fat Wreck Chords', 'duration': '4:46', 'verified_music': False} 
[ytmdl]:[22/11/2020 20:12:16]:  Downloading NOFX - Fish in a Gun Barrel w/ Fat Mike introduction in 320kbps 
[yt]:[22/11/2020 20:12:16]:  Saving the files to: /home/david/.cache/ytmdl 
[yt]:[22/11/2020 20:12:16]:  /home/david/.cache/ytmdl/NOFX#-#Fish#in#a#Gun#Barrel#w##Fat#Mike#introduction.mp3 
[yt]:[22/11/2020 20:12:18]:  ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytmdl]:[22/11/2020 20:12:18]:  ERROR: ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
```

## Description

Unable to extract JS player URL

**Comment by deepjyoti30** [comment]
@Ramiferous Seems like an issue of `youtube-dl`.

Can you try the fix in [this](https://github.com/l1ving/youtube-dl/issues/12) issue? However, this should probably be fixed in the next version of `youtube-dl`.

Also, this is not happening for all the songs, is it?

**Comment by Ramiferous** [comment]
Cant seem to find extractor\youtube.py so not really sure how to apply this fix?

And yes, I did manage to download one song so it has worked. Cant see to find another song that it'll download though.

**Comment by deepjyoti30** [comment]
@Ramiferous Totally a `youtube-dl` issue. If you want, you can search the `youtube-dl` source for issues and raise one but I think I'm unable to help.

**Comment by Ramiferous** [comment]
No worries, will see if the next version of `youtube-dl` fixes it.

**Comment by Ramiferous** [comment]
Actually, it's not yet solved so will reopen until this gets sorted out in upstream `youtube-dl`

**Comment by deepjyoti30** [comment]
@Ramiferous Is this fixed in `youtube-dl`? Feel free to close this when that happens.

**Comment by Ramiferous** [comment]
> 
> 
> @Ramiferous Is this fixed in `youtube-dl`? Feel free to close this when that happens.

Just updated to youtube-dl version 2021.03.03 and still get the same error

**Comment by Ramiferous** [comment]
I'm going to be using another tool for the same purpose as this which works for me: [tyfzf](https://github.com/pystardust/ytfzf)
I'll close this issue now.
