### ISSUE TITLE
[Bug] Playlist stops loading when there is a video that has [Video blocked in country]

### ISSUE THREAD

**Issue by J0rdyV** [deepjyoti30/ytmdl#128]
# Bug report
Playlist stops loading when there is a video that is unavailable in your country, and error gets thrown.
Even though there are some songs in the playlist that do not have the tag [Video blocked in country].

## Checklist

[x] I have searched for similar bugs in the issues.
[x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2020.11.20-1`
- Youtube-dl version: `2020.11.17`

## How Ytmdl was installed?
With yay ( from the aur ) and youtube-dl with pacman

Write here how you installed ytmdl. If it was through pip or some other way.
yay ytmdl
pacman -S youtube-dl

## Console Log

```console
~ ytmdl https://www.youtube.com/playlist\?list\=PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68 --level DEBUG
 ==>  Youtube playlist passed...extracting!
 ==>  Playlist: PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68
 ==>  18 songs found
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=[], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url='https://www.youtube.com/watch?v=g6wvGks0D6Y')
 ==>  []
 ==>  https://www.youtube.com/watch?v=g6wvGks0D6Y
ERROR: Video unavailable
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2029, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 469, in <module>
    extract_data()
  File "/usr/bin/ytmdl", line 462, in extract_data
    main(args)
  File "/usr/bin/ytmdl", line 215, in main
    song_name = yt.get_title(args.url)
  File "/usr/lib/python3.8/site-packages/ytmdl/yt.py", line 327, in get_title
    data = ydl.extract_info(url, False)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Video unavailable
```

## Description

Playlist stops loading when there is a video that is unavailable in your country, and error gets thrown.
Even though there are some songs in the playlist that do not have the tag [Video blocked in country],
ytmdl gives an error and does not download any songs.

**Comment by deepjyoti30** [comment]
@J0rdyV Thanks for the report. Seems like an unhandled exception. I will fix this.

Did you happen to try the `--ignore-errors` flag?

**Comment by J0rdyV** [comment]
Seems to give me the same output.

```
ytmdl https://www.youtube.com/playlist\?list\=PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68 --ignore-errors --level DEBUG
 ==>  Youtube playlist passed...extracting!
 ==>  Playlist: PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68
 ==>  18 songs found
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=[], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=True, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url='https://www.youtube.com/watch?v=g6wvGks0D6Y')
 ==>  []
 ==>  https://www.youtube.com/watch?v=g6wvGks0D6Y
ERROR: Video unavailable
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2029, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: Video unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 469, in <module>
    extract_data()
  File "/usr/bin/ytmdl", line 462, in extract_data
    main(args)
  File "/usr/bin/ytmdl", line 215, in main
    song_name = yt.get_title(args.url)
  File "/usr/lib/python3.8/site-packages/ytmdl/yt.py", line 327, in get_title
    data = ydl.extract_info(url, False)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 820, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Video unavailable
```

**Comment by deepjyoti30** [comment]
@J0rdyV Thanks for reporting the issue. As I said this was an unhandled exception and should be fixed in de35931a9caf9fdae02cfe43

However, the playlist you provided is working all right for me so please do try the above commit and let me know if it still breaks!

**Comment by J0rdyV** [comment]
@deepjyoti30 Thanks for looking at this issue :)
I still get the same error as before. I downloaded this repo, did `git checkout unstable` and `sudo python setup.py install`.
The version gives me the same number, so I'm unsure if it's installed correctly.

This is the output I get from youtube-dl when downloading the playlist, hopefully this helps.
```
youtube-dl --ignore-errors --format bestaudio --extract-audio --audio-format mp3 --audio-quality 160K --output "%(title)s.%(ext)s" --yes-playlist 'https:
//www.youtube.com/playlist?list=PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68'
[youtube:tab] PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68: Downloading webpage
[download] Downloading playlist: Netsky - Second Nature album
[youtube:tab] playlist Netsky - Second Nature album: Downloading 18 videos
[download] Downloading video 1 of 18
[youtube] g6wvGks0D6Y: Downloading webpage
ERROR: This video is not available.
[download] Downloading video 2 of 18
[youtube] uLhDtyvsMz0: Downloading webpage
[youtube] uLhDtyvsMz0: Downloading js player 77da52cd
[youtube] uLhDtyvsMz0: Downloading js player 77da52cd
[download] Destination: Netsky & Rudimental - Blend (ft. Afronaut Zu).webm
[download] 100% of 3.37MiB in 00:00
[ffmpeg] Destination: Netsky & Rudimental - Blend (ft. Afronaut Zu).mp3
Deleting original file Netsky & Rudimental - Blend (ft. Afronaut Zu).webm (pass -k to keep)
[download] Downloading video 3 of 18
....
```

**Comment by deepjyoti30** [comment]
@J0rdyV Since you installed initially from the AUR, it is possible you have two versions installed?!

Can you please uninstall the one installed from AUR using `yay -R ytmdl`. Once done, remove all the installed versions from pip as well by using `pip uninstall ytmdl`.

Now try to check if `ytmdl` is still installed by running `ytmdl --help`. If it is still installed, remove using pip again.

Basically, you have to remove all the versions that are installed.

Once you see that `ytmdl --help` shows `ytmdl command not found`, this means you are ready to install the latest commits.
Now go to the ytmdl directory, checkout unstable and install `python setup.py install`.

Once above is done, try running `ytmdl` with the playlist. It should possibly be fixed. If you do face it, please share the logs from `ytmdl` again.

**Comment by J0rdyV** [comment]
Hi, sorry but this did not fix the issue.

**Comment by deepjyoti30** [comment]
@J0rdyV Thanks for replying.

Should be fixed in f5db5938ed2c2fd714a6824d5d3cf

Do consider trying out the latest commits.

**Comment by J0rdyV** [comment]
Worked perfectly! Thanks :D

```
✓ ytmdl https://www.youtube.com/playlist\?list\=PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68 --ignore-errors --level DEBUG
 ==> Logger running in DEBUG mode
 ==> Passed args: Namespace(SONG_NAME=['https://www.youtube.com/playlist?list=PL-7nmTLmYrj0VQIdGrvSyoubCG4CtDC68'], quiet=False, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, proxy=None, url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=True, title_as_name=False, level='DEBUG', disable_file=False, list_level=False)
 ==> Youtube playlist passed...extracting!
 ==> Playlist: Netsky - Second Nature album
 ==> 18 songs found
 ==> []
 ==> https://www.youtube.com/watch?v=g6wvGks0D6Y
ERROR: This video is not available.
 ==> None
 ==> Searching to see if already present in /home/jordy/packages/ytmdl
 ==> proxy passed: None
 ==> Passed format: mp3
 ==> Downloading Hold On in 320kbps
 ==> Saving the files to: /home/jordy/.cache/ytmdl
 ==> /home/jordy/.cache/ytmdl/Hold#On.mp3
ERROR: This video is not available.
 ==> ERROR: This video is not available.
 ==> --ignore-errors passed. Skipping this song!
 ==> []
 ==> https://www.youtube.com/watch?v=uLhDtyvsMz0
 ==> Current extracted title for the song is: `netsky & rudimental blend ft. afronaut zu`
 ==> Most extracted titles are not accurate and they affect the meta search
Would you like to change [y/n] (y):
```
