### ISSUE TITLE
`is unauthorized` for `http://www.youtube.com/oembed?url={}&format=json` url

### ISSUE THREAD

**Issue by demin-dmitriy** [deepjyoti30/ytmdl#138]
# Bug report

## Checklist

* [x] I have searched for similar bugs in the issues.
* [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2020.11.20-1`
- Youtube-dl version: `2020.12.12`

## How Ytmdl was installed?

pip

## Description

At some moment all videos began to give me "is unauthorized" error. Digging into what causes it, I found that in `scan_video` function http reqest receives message `SSL is required to perform this operation.` when trying to access `http://www.youtube.com/oembed?url={}&format=json`. Changing `http` to `https` in the link fixed this issue for me.

**Comment by deepjyoti30** [comment]
@demin-dmitriy  Are you sure you have not exceeded the rate limit??

It seems like a rate limit related issue. You can not use the app for a while and try again and it should probably work again.

**Comment by demin-dmitriy** [comment]
Yes, I am sure it is not because of the rate limit. It fails with `http` every time, and succeeds with `https` every time. Here is exact command which I run: `ytmdl --skip-meta --url "https://www.youtube.com/watch?v=pR1aGhjDL9M"`.

It even says in response that SSL is required.

**Comment by deepjyoti30** [comment]
@demin-dmitriy Thanks for reporting the issue. It was occuring due to a bug in checking if the passed URL is a playlist.

It should be fixed in 48200d9fdf22e2f

You can try out the commit and close this issue.

**Comment by demin-dmitriy** [comment]
I still have the same error. And fix which I was doing locally (with changing http to https) still works for me. Here is the patch:

```patch
*** "yt-orig.py"	2020-12-21 09:47:07.166638000 +0300
--- yt.py	2020-12-21 09:47:15.446553254 +0300
*************** def scan_video(url, proxy):
*** 233,239 ****
      if proxy is not None:
          proxies['http'] = proxy
      try:
!         search_tmplt = "http://www.youtube.com/oembed?url={}&format=json"
          search_url = search_tmplt.format(url)
          r = requests.get(search_url, proxies=proxies)
  
--- 233,239 ----
      if proxy is not None:
          proxies['http'] = proxy
      try:
!         search_tmplt = "https://www.youtube.com/oembed?url={}&format=json"
          search_url = search_tmplt.format(url)
          r = requests.get(search_url, proxies=proxies)

```

**Comment by deepjyoti30** [comment]
@demin-dmitriy Thanks. Will make that change. I thought your issue was occurring for playlists that had the `http` instead of `https`.

**Comment by deepjyoti30** [comment]
Added in `2021.1.14`.

**Comment by DocMAX** [comment]
I have similar(?) issue:
```
 ==> https://www.youtube.com/watch?v=C7-kAfQkZ9A: is unauthorized 
Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 562, in <module>
    extract_data()
  File "/usr/bin/ytmdl", line 555, in extract_data
    main(args)
  File "/usr/bin/ytmdl", line 264, in main
    link, yt_title = search(song_name=song_name, args=args)
TypeError: cannot unpack non-iterable NoneType object

```
